functionsDirectory = "/Users/tiffanywright/Documents/GitHub/The-Daily-Session/netlify/functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/tiffanywright/Documents/GitHub/The-Daily-Session/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/tiffanywright/Documents/GitHub/The-Daily-Session/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/api/sessions"
to = "/.netlify/functions/sessions"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/create-checkout-session"
to = "/.netlify/functions/create-checkout-session"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/verify-checkout-session"
to = "/.netlify/functions/verify-checkout-session"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/member"
to = "/.netlify/functions/airtable-members"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/providers"
to = "/.netlify/functions/providers"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/provider-applications"
to = "/.netlify/functions/provider-applications"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/visitors-locked"
to = "/.netlify/functions/visitors-locked"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/companies"
to = "/.netlify/functions/companies"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/saved-classes"
to = "/.netlify/functions/saved-classes"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/studio-application"
to = "/.netlify/functions/studio-application"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]