[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/sessions"
  to = "/.netlify/functions/sessions"
  status = 200

[[redirects]]
  from = "/api/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200

[[redirects]]
  from = "/api/verify-checkout-session"
  to = "/.netlify/functions/verify-checkout-session"
  status = 200

[[redirects]]
  from = "/api/member"
  to = "/.netlify/functions/airtable-members"
  status = 200

[[redirects]]
  from = "/api/providers"
  to = "/.netlify/functions/providers"
  status = 200

[[redirects]]
  from = "/api/companies"
  to = "/.netlify/functions/companies"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
